# Generated by Django 5.1.1 on 2024-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=6),
            preserve_default=False,
        ),
    ]
